---
title: Gumawa ng listahan
hero_image: mga imahe / banner.png
description: Gumawa ng isang bagong listahan
theme: pula #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 1 #possible values: 1, 2 or 3
listed: false
ingredient: true
copyedit: true
curriculum: tagalikha, disenyo-0, programming-0, phys-comp-0, paggawa-0, komunidad-0
interests: ""
technologies: "scratch"
site_areas:
steps:
  - 
    title: Gumawa ng listahan
