---
title: Ustvari seznam
hero_image: images / banner.png
description: Ustvari nov seznam
theme: rdeča
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: ustvarjalec, oblikovanje-0, programiranje-0, fiz-rač-0, izdelava-0, skupnost-0
interests: ""
technologies: "scratch"
site_areas:
steps:
  - 
    title: Ustvari seznam
