---
title: 리스트 만들기
hero_image: images / banner.png
description: 새 리스트 만들기
theme: red
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: 작성자, 디자인 -0, 프로그래밍 -0, phys-comp-0, 제조 -0, 커뮤니티 -0
interests: ""
technologies: "scratch"
site_areas:
steps:
  - 
    title: 리스트 만들기
